name: burnichmedia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8404503853525966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e5e5e'
    - '#ef4d23'
    - '#000000'
    - '#ffffff'
    - '#aaaaaa'
  brandStrength: 0.2591323829255998
  lightness: 0.25056893448345363
  saturation: 0.7505945884622633
  rhythmicContrast: 0.02333550783805549
purpose: []
